import { NextRequest, NextResponse } from 'next/server'
import { buildMonthlyStats, generatePDFReport } from '@/services/report'
import { format, subMonths } from 'date-fns'

// Called by Vercel Cron (see vercel.json)
// Secured by CRON_SECRET header
export async function GET(req: NextRequest) {
  const secret = req.headers.get('x-cron-secret')
  if (secret !== process.env.CRON_SECRET) {
    return NextResponse.json({ error: 'Unauthorised' }, { status: 401 })
  }

  const now = new Date()
  const prev = subMonths(now, 1)
  const year = prev.getFullYear()
  const month = prev.getMonth() + 1

  try {
    const stats = await buildMonthlyStats(year, month)

    if (stats.length === 0) {
      return NextResponse.json({ message: 'No data for previous month', year, month })
    }

    const pdfBuffer = await generatePDFReport(year, month, stats)
    const monthLabel = format(prev, 'MMMM yyyy')

    const recipientEmail = process.env.REPORT_RECIPIENT_EMAIL
    const emailApiKey = process.env.EMAIL_API_KEY

    if (recipientEmail && emailApiKey) {
      // Send via Resend (or replace with your preferred provider)
      await sendEmailWithAttachment({
        to: recipientEmail,
        subject: `WC Hospital Patient Feedback Report — ${monthLabel}`,
        text: `Please find attached the Western Cape public hospital patient feedback report for ${monthLabel}.\n\nThis report was automatically generated by the WC Hospital Feedback System.`,
        filename: `WC-Hospital-Feedback-${format(prev, 'MMMM-yyyy')}.pdf`,
        pdfBuffer,
        apiKey: emailApiKey,
      })

      return NextResponse.json({
        message: `Report for ${monthLabel} generated and emailed to ${recipientEmail}`,
        hospitals: stats.length,
        total_submissions: stats.reduce((s, h) => s + h.total, 0),
      })
    }

    // If email not configured, just acknowledge successful generation
    return NextResponse.json({
      message: `Report for ${monthLabel} generated (no email configured)`,
      hospitals: stats.length,
      total_submissions: stats.reduce((s, h) => s + h.total, 0),
      note: 'Set REPORT_RECIPIENT_EMAIL and EMAIL_API_KEY to enable email delivery',
    })
  } catch (err) {
    console.error('[CRON] monthly-report error:', err)
    return NextResponse.json({ error: 'Failed to generate report' }, { status: 500 })
  }
}

// Simple Resend integration — replace with SendGrid/Mailgun if preferred
async function sendEmailWithAttachment({
  to, subject, text, filename, pdfBuffer, apiKey,
}: {
  to: string
  subject: string
  text: string
  filename: string
  pdfBuffer: Buffer
  apiKey: string
}) {
  const base64Pdf = pdfBuffer.toString('base64')

  const res = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${apiKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      from: 'WC Health Feedback <noreply@yourdomain.co.za>',
      to: [to],
      subject,
      text,
      attachments: [
        {
          filename,
          content: base64Pdf,
        },
      ],
    }),
  })

  if (!res.ok) {
    const err = await res.text()
    throw new Error(`Email send failed: ${err}`)
  }
}
